package com.example.domain.model.details

data class MovieDetails(
    val originalLanguage: String?,
    val imdbId: String?,
    val video: Boolean?,
    val title: String,
    val backdropPath: String?,
    val revenue: Int?,
    val genres: List<Genres>?,
    val popularity: Double?,
    val productionCountries: List<ProductionCountries>?,
    val id: Int,
    val voteCount: Int?,
    val budget: Int?,
    val overview: String,
    val originalTitle: String?,
    val runtime: Int?,
    val posterPath: String?,
    val spokenLanguages: List<SpokenLanguages>?,
    val productionCompanies: List<ProductionCompanies?>?,
    val releaseDate: String?,
    val voteAverage: Double,
    val belongsToCollection: BelongsToCollection?,
    val tagline: String?,
    val adult: Boolean?,
    val homepage: String?,
    val status: String?,
    val shortInfoAboutFilm: String,
)